# Generated by Django 6.0.6 on 2026-08-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="description",
            field=models.TextField(blank="true", null="true"),
        ),
    ]
